---
###############################################################################
#
###############################################################################


IVRAAS_VERSION: G02R09C06


WEB_APPS:
 - { name: gv-admmsgvocale-svi  , version: V12.4.12  , vhost: gv-admmsgvocale-svi-amea.dmz.cloud.mbs }
 - { name: gv-authent		, version: V12.4.12  , vhost: gv-authent-amea.dmz.cloud.mbs          }
 - { name: gv-provisioning 	, version: V1.1.0    , vhost: gv-provisioning-amea.dmz.cloud.mbs     } 
 - { name: gv-switchingservice	, version: V1.12.1   , vhost: gv-switchingservice-amea.dmz.cloud.mbs }
 - { name: gv-webservices 	, version: V12.4.12  , vhost: gv-webservices-amea.dmz.cloud.mbs      }
 - { name: gv-svifiles	 	, version: V12.4.12  , vhost: gv-svifiles-amea.dmz.cloud.mbs 	     }
 - { name: gv-admin-stp 	, version: V2.10.5.1 , vhost: gv-authent-amea.dmz.cloud.mbs 	     } 
 - { name: gv-adv 		, version: V12.4.12  , vhost: gv-authent-amea.dmz.cloud.mbs 	     }
 - { name: gv-stats 		, version: V2.10.5.1 , vhost: gv-authent-amea.dmz.cloud.mbs 	     }
 - { name: gv-vocalmestre	, version: V12.4.12  , vhost: gv-authent-amea.dmz.cloud.mbs 	     } 


MYSQL_IP: mysql_server


BATCHES:
 - { name: convPcnV2                    , type: batch     , version: V2.1.0    }
 - { name: gv-batch                     , type: cronbatch , version: V12.4.12  }
 - { name: gv-batch-stp                 , type: cronbatch , version: V2.10.5.1 }
 - { name: gv-tools                     , type: cronbatch , version: V12.4.12  }
 - { name: stats-calculator             , type: batch     , version: V2.1.0    }
 - { name: stats-manager                , type: batch     , version: V2.1.0    }
 - { name: stats-manager-reintegration  , type: batch     , version: V2.1.0    }
 - { name: stats-rapatriement           , type: cronbatch , version: V2.1.0    }
 - { name: stats-utilities              , type: cronbatch , version: V2.1.0    }



