---

MYSQL_ROOT_PASS: password123

DATA_BASES:
  - StatVoxProdV2
  - StatVoxProdV2Tmp
  - exploitvocalAdmin
  - exploitvocalProd
  - gvw
  - gvw_logs

SQL_SCRIPTS:
  - db-stats-struct.sql
  - db-stats-data.sql
  - db-gvw-initUserAndDb.sql   
  - db-gvw-struct_12.4.12.sql   
  - db-gvw_logs-initUserAndDb.sql 
  - db-gvw_logs-struct_12.4.12.sql

MYSQL_REPLACE:
- { dest: "{{EXTRACT_DIR}}/sql_scripts/db-gvw_logs-struct_12.4.12.sql" , regexp: R8500@rapport.ivraas , replace: R8500@rapport.ivraas }
- { dest: "{{EXTRACT_DIR}}/sql_scripts/db-gvw-struct_12.4.12.sql" , regexp: LOCAL_COUNTRY , replace: LOCAL_COUNTRY }
