---

#############################################################
#               Install apache http server                  #
#############################################################

- name: Ensure apache http server is installed
  yum:
    name: httpd
    state: latest
  tags: apache

- name: Ensure http server is enabled
  service:
    name: httpd
    enabled: yes
  tags: apache


#############################################################
#               Apache server Configuration                 #
#############################################################

- name: File-- Create web application and logs directories
  file:
    dest: "{{item.dest}}"
    state: "{{item.state}}"
  with_items: "{{APACHE_FILE}}"
  tags: apache

- name: Copy-- Copy  modules/ to {{APACHE_CONF}}/modules/
  copy:
    src: "{{item.src}}" 
    dest: "{{item.dest}}"
  with_items: "{{APACHE_COPY}}"
  tags: apache

- name: Template-- Templating mod_jk.conf, worker.properties and apache virtual hosts configuration files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items: "{{APACHE_TEMPLATE}}"
  notify: restart httpd
  tags: apache

- name: Lineinfile-- Modify httpd.conf 
  lineinfile: 
    dest: "{{item.dest}}"
    line: "{{item.line}}"
  with_items: "{{APACHE_LINEINFILE}}"
  tags: apache

