---

#############################################################
#               Install apache http server                  #
#############################################################

- name: Ensure apache http server is installed
  yum:
    name: httpd
    state: latest
  become: yes
  tags: apache

- name: Ensure http server is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
  tags: apache


#############################################################
#                    Add module mod_jk                      #
#############################################################

- name: Add mod_jk module in httpd.conf
  lineinfile: 
    dest: "{{item.dest}}"
    line: "{{item.line}}"
  with_items: "{{APACHE_LINEINFILE}}"
  become: yes
  notify: restart httpd
  tags: apache


- name: Copy mod_jk module and its configuration and worker files
  copy:
    src: "{{item.src}}" 
    dest: "{{item.dest}}"
  with_items: "{{APACHE_COPY}}"
  become: yes
  notify: restart httpd
  tags: apache

- name: Create web application and logs directories
  file:
    path: "{{item.path}}"
    state: directory
  with_items: "{{APACHE_FILE}}"
  become: yes
  tags: apache

