---

#############################################################
#               Install apache http server                  #
#############################################################

- name: Ensure apache http server is installed
  yum:
    name: httpd
    state: latest
  tags: apache

- name: Ensure http server is enabled
  service:
    name: httpd
    enabled: yes
  tags: apache


#############################################################
#                    Add module mod_jk                      #
#############################################################

- name: Modify {{APACHE_CONF}}/conf/httpd.conf 
  lineinfile: 
    dest: "{{item.dest}}"
    line: "{{item.line}}"
  with_items: "{{APACHE_LINEINFILE}}"
  notify: restart httpd
  tags: apache

- name: Copy module/ to {{APACHE_CONF}}/modules/
  copy:
    src: "{{item.src}}" 
    dest: "{{item.dest}}"
  with_items: "{{APACHE_COPY}}"
  notify: restart httpd
  tags: apache

- name: Create web application and logs directories
  file:
    dest: "{{item.dest}}"
    state: "{{item.state}}"
  with_items: "{{APACHE_FILE}}"
  tags: apache

- name: Templating {{APACHE_CONF}}/conf/mod_jk.conf
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items: "{{APACHE_TEMPLATE}}"
  tags: apache


