--- 

########################################

- name: IVRaaS was 
  hosts: IVRaaS_servers
  gather_facts: False

  roles:
   - common

########################################

- name: IVRaaS was 
  hosts: was
  gather_facts: False

  roles:
   - pli-apache
   - pli-tomcat
   - was

#########################################

- name: IVRaaS db 
  hosts: test
  gather_facts: False

  roles:
   - pli-mysql
   - db

########################################

- name: IVRaaS batch 
  hosts: batch
  gather_facts: False

  roles:
   - batch
