---

##########################################################################################################################
#						apache tasks variables							 #
##########################################################################################################################

APACHE_FILE:
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}/ROOT"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/ROOT"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}/ROOT"	 	, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}/ROOT"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.5.vhost}}/ROOT"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/admin-stp"	, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/stats"	, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/adv1"		, state: directory }
 - { dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/vocalmestre1" , state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.0.vhost}}/current" 	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.1.vhost}}/current"	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.2.vhost}}/current"	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.3.vhost}}/current" 	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.4.vhost}}/current"	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/{{WEB_APPS.5.vhost}}/current"	, state: directory }
 - { dest: "{{WEB_LOG_BASE}}/mod_jk/current"			, state: directory }


APACHE_TEMPLATE:
 - { src: gv-admmsgvocale-svi.conf.j2 , dest: "{{APACHE_CONF}}/{{WEB_APPS.0.vhost}}.conf" , var1: "{{WEB_APPS.0.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 - { src: gv-authent.conf.j2 	      , dest: "{{APACHE_CONF}}/{{WEB_APPS.1.vhost}}.conf" , var1: "{{WEB_APPS.1.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 - { src: gv-provisioning.conf.j2     , dest: "{{APACHE_CONF}}/{{WEB_APPS.2.vhost}}.conf" , var1: "{{WEB_APPS.2.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 - { src: gv-switchingservice.conf.j2 , dest: "{{APACHE_CONF}}/{{WEB_APPS.3.vhost}}.conf" , var1: "{{WEB_APPS.3.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 - { src: gv-webservices.conf.j2      , dest: "{{APACHE_CONF}}/{{WEB_APPS.4.vhost}}.conf" , var1: "{{WEB_APPS.4.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 - { src: gv-svifiles.conf.j2         , dest: "{{APACHE_CONF}}/{{WEB_APPS.5.vhost}}.conf" , var1: "{{WEB_APPS.5.vhost}}" , var2: "{{WEB_APP_BASE}}" , var3: "{{WEB_LOG_BASE}}" }
 

##########################################################################################################################
#						tomcat tasks variables							 #
##########################################################################################################################


TOMCAT_FILE:
 - { path: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.0.vhost}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.2.vhost}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.3.vhost}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.4.vhost}}" , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.5.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}" 	   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}" 	   , state: directory }


TOMCAT_UNARCHIVE: 
 - { src: "{{WEB_ZIP_FILENAME}}.zip"						     , dest: "{{EXTRACT_DIR}}" 					 , remote_src: no }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}-webapp-{{WEB_APPS.0.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}-webapp-{{WEB_APPS.1.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}-webapp-{{WEB_APPS.2.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}-webapp-{{WEB_APPS.3.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}-webapp-{{WEB_APPS.4.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.5.name}}-webapp-{{WEB_APPS.5.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.5.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}-webapp-{{WEB_APPS.6.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}-webapp-{{WEB_APPS.7.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}" 		 , remote_src: yes}  
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}-webapp-{{WEB_APPS.8.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}" 		 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}-webapp-{{WEB_APPS.9.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}" 		 , remote_src: yes}  
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}/binpackage/{{WEB_APPS.0.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}/ROOT" 	 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}/binpackage/{{WEB_APPS.1.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/ROOT" 	 , remote_src: yes} 
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}/binpackage/{{WEB_APPS.2.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}/ROOT"        , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}/binpackage/{{WEB_APPS.3.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}/ROOT" 	 , remote_src: yes} 
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}/binpackage/{{WEB_APPS.4.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT" 	 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.5.name}}/binpackage/{{WEB_APPS.5.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.5.vhost}}/ROOT" 	 , remote_src: yes} 
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}/binpackage/{{WEB_APPS.6.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}/admin-stp" 	 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}/binpackage/{{WEB_APPS.7.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1" 	 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}/binpackage/{{WEB_APPS.8.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}/stats" 	 , remote_src: yes}
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}/binpackage/{{WEB_APPS.9.name}}.war"   , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/vocalmestre1", remote_src: yes} 


TOMCAT_SYNCHRONIZE:
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}/ROOT/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/ROOT/META-INF"	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}/ROOT/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}/ROOT/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.5.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.5.vhost}}/ROOT/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}/admin-stp/META-INF"    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}/stats/META-INF" 	    }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}/conf/" , dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/vocalmestre1/META-INF" }
 
TOMCAT_COPY:
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.0.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.0.vhost}}/ROOT.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.1.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/ROOT.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.2.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.2.vhost}}/ROOT.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.3.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.3.vhost}}/ROOT.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.4.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.4.vhost}}/ROOT.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.6.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/admin-stp.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.7.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/adv1.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.8.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/stats.xml" 	  , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{WEB_APPS.9.name}}/conf/context.xml" , dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/vocalmestre1.xml" , remote_src: yes }


TOMCAT_LINEINFILE:
 - dest: "{{TOMCAT_CONF}}/server.xml"
   regexp: '<Connector port="8009"'
   line: <Connector port="8009" maxThreads="800" connectionTimeout="60000" minSpareThreads="25" maxSpareThreads="75" enableLookups="false" protocol="AJP/1.3" redirectPort="8443" />

 - dest: "{{TOMCAT_CONF}}/server.xml"
   regexp: '<Engine name="Catalina" defaultHost="localhost"'
   line: <Engine name="Catalina" defaultHost="localhost" jvmRoute="localhost">

# - dest: "{{TOMCAT_CONF}}/tomcat{{TOMCAT_VERSION}}.conf"
#   regexp: 'JAVA_OPTS='
#   line: JAVA_OPTS="${JAVA_OPTS} -Xmx1536m -Xms1024m -Xmn512m -XX:MaxPermSize=512m -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory"
#

TOMCAT_BLOCKINFILE:
 - dest: "{{TOMCAT_CONF}}/server.xml"
   insertafter: "</Host>"
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
   block: |
      <Host name="{{WEB_APPS.1.vhost}}" appBase="{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
      </Host>
 
      <Host name="{{WEB_APPS.0.vhost}}" appBase="{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
      </Host>
 
      <Host name="{{WEB_APPS.3.vhost}}" appBase="{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
      </Host>
 
      <Host name="{{WEB_APPS.4.vhost}}" appBase="{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
      </Host>
 
      <Host name="{{WEB_APPS.2.vhost}}" appBase="{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
      </Host>


TOMCAT_REPLACE:
############################################# context files in tomcat ##############################################
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.0.vhost}}/ROOT.xml" 
   changes:
    - { regexp: /usr2/web/gv-admmsgvocale-svi-amea.dmz.cloud.mbs , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.1.vhost}}/ROOT.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.2.vhost}}/ROOT.xml"
   changes:
    - { regexp: /usr2/web/gv-provisioning-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.3.vhost}}/ROOT.xml"
   changes:
    - { regexp: /usr2/web/gv-switchingservice-amea.dmz.cloud.mbs , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.4.vhost}}/ROOT.xml"
   changes:
    - { regexp: /usr2/web/gv-webservices-amea.dmz.cloud.mbs	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.6.vhost}}/admin-stp.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.7.vhost}}/adv1.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.8.vhost}}/stats.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}" }
 - dest: "{{TOMCAT_CONF}}/Catalina/{{WEB_APPS.9.vhost}}/vocalmestre1.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}" }
#########################################  admmsgvocale Webapp META-INF  ############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}/ROOT/META-INF/context.xml" 
   changes:   
    - { regexp: /usr2/web/gv-admmsgvocale-svi-amea.dmz.cloud.mbs , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.0.vhost}}/ROOT/META-INF/hibernate.cfg.xml" 
   changes:  
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 			 , replace: "{{MYSQL_IP}}" }
############################################  authent Webapp META-INF  ##############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/ROOT/META-INF/context.xml"
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.1.vhost}}/ROOT/META-INF/hibernate.cfg.xml"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 	 		 , replace: "{{MYSQL_IP}}" }
##########################################  provisioning Webapp META-INF ############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}/ROOT/META-INF/context.xml"         
   changes:
    - { regexp: /usr2/web/gv-provisioning-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.2.vhost}}" }
########################################  switchingservice Webapp META-INF ##########################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}/ROOT/META-INF/context.xml"         
   changes:
    - { regexp: /usr2/web/gv-switchingservice-amea.dmz.cloud.mbs , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.3.vhost}}/ROOT/META-INF/application.properties"         
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 			 , replace: "{{MYSQL_IP}}" }
############################################  webservice Webapp META-INF #############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT/META-INF/context.xml"         
   changes:
    - { regexp: /usr2/web/gv-webservices-amea.dmz.cloud.mbs	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT/META-INF/hibernate.cfg.xml"         
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.4.vhost}}/ROOT/META-INF/hibernateStatMaster.cfg.xml"         
   changes:
   - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
############################################  admin-stp Webapp META-INF ##############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}/admin-stp/META-INF/context.xml"    
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.6.vhost}}/admin-stp/META-INF/application.properties"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
###############################################  adv Webapp META-INF #################################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1/META-INF/context.xml"         
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1/META-INF/hibernate.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1/META-INF/hibernateStat.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.7.vhost}}/adv1/META-INF/hibernateStatMaster.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
#################################################  stats Webapp META-INF ###############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}/stats/META-INF/context.xml"        
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}" }
# - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.8.vhost}}/stats/META-INF/application.properties"    
#   changes:
#    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
##############################################  vocalmestre Webapp META-INF ############################################
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/vocalmestre1/META-INF/context.xml" 
   changes:
    - { regexp: /usr2/web/gv-authent-amea.dmz.cloud.mbs 	 , replace: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/adv1/META-INF/hibernate.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/adv1/META-INF/hibernateStat.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }
 - dest: "{{WEB_APP_BASE}}/{{WEB_APPS.9.vhost}}/adv1/META-INF/hibernateStatMaster.cfg.xml"    
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs	 		 , replace: "{{MYSQL_IP}}" }


