---

EXTRACT_DIR: "/images/IVRaaS_{{IVRAAS_VERSION}}"

BATCH_APP_BASE: "/opt/application/ivraas/{{IVRAAS_VERSION}}"

BATCH_ZIP_FILENAME: batch

BATCHES:
 - { name: convPcnV2                    , type: batch     , version: "{{hostvars['localhost'].BATCHES_VERSIONS.0}}" }
 - { name: gv-batch                     , type: cronbatch , version: "{{hostvars['localhost'].BATCHES_VERSIONS.1}}" }
 - { name: gv-stats-stp                 , type: cronbatch , version: "{{hostvars['localhost'].BATCHES_VERSIONS.2}}" }
 - { name: gv-tools                     , type: cronbatch , version: "{{hostvars['localhost'].BATCHES_VERSIONS.3}}" }
 - { name: stats-calculator             , type: batch     , version: "{{hostvars['localhost'].BATCHES_VERSIONS.4}}" }
 - { name: stats-manager                , type: batch     , version: "{{hostvars['localhost'].BATCHES_VERSIONS.5}}" }
 - { name: stats-manager-reintegration  , type: batch     , version: "{{hostvars['localhost'].BATCHES_VERSIONS.6}}" }
 - { name: stats-rapatriement           , type: cronbatch , version: "{{hostvars['localhost'].BATCHES_VERSIONS.7}}" }
 - { name: stats-utilities              , type: cronbatch , version: "{{hostvars['localhost'].BATCHES_VERSIONS.8}}" }



BATCH_STARTUP:
 - { SERVICE: gvStatCalculator  , SRC: "{{BATCH_APP_BASE}}/batch/stats-calculator/batch/bin/init.d/gvStatCalculator"   }
 - { SERVICE: gvStatManager     , SRC: "{{BATCH_APP_BASE}}/batch/stats-manager/batch/bin/init.d/gvStatManager"         }
 - { SERVICE: convPcnV2         , SRC: "{{BATCH_APP_BASE}}/batch/convPcnV2/batch/bin/init.d/convPcnV2"                 }

######################################################################################################################

BATCH_GROUP:
 - { name: stats       , gid: 30000 }
 - { name: serveur     , gid: 30001 }
 - { name: ivrgroup    , gid: 3520  }

BATCH_USER:
 - { name: stats       , uid: 30000 , group: stats       }
 - { name: serveur     , uid: 30001 , group: serveur     }
 - { name: ivruser     , uid: "{{hostvars[groups['was'][0]].ivruser_id}}"  , group: ivrgroup    }


BATCH_FILE_1:
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch"  , owner: stats   , group: stats   , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch"  , owner: serveur , group: serveur , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch"  , owner: serveur , group: serveur , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch"	, owner: serveur , group: serveur , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch"  , owner: stats   , group: stats   , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch"  , owner: stats   , group: stats   , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}/batch"  , owner: stats   , group: stats   , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch" 	, owner: stats   , group: stats   , state: directory }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch"  , owner: stats   , group: stats   , state: directory }
 - { path: /mnt/statVox2/var/data 	   			, owner: stats   , group: stats   , state: directory }
 - { path: /mnt/statVox2/var/pcn 	   			, owner: stats   , group: stats   , state: directory }
 - { path: /mnt/statVox2/var/stats	   			, owner: stats   , group: stats   , state: directory }
 - { path: /mnt/statVox2/var/archive 	   			, owner: stats   , group: stats   , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}" 		, owner: root    , group: root    , state: directory }
 - { path: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}"  		, owner: root    , group: root    , state: directory }
 - { path: "{{BATCH_APP_BASE}}/logs"  				, owner: stats   , group: stats   , state: directory }

BATCH_COPY:
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/libperl.gz"    , dest: "/tmp" }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.0.name}}-{{BATCHES.0.type}}-V{{BATCHES.0.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.1.name}}-{{BATCHES.1.type}}-V{{BATCHES.1.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.2.name}}-{{BATCHES.2.type}}-V{{BATCHES.2.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.3.name}}-{{BATCHES.3.type}}-V{{BATCHES.3.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.4.name}}-{{BATCHES.4.type}}-V{{BATCHES.4.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.5.name}}-{{BATCHES.5.type}}-V{{BATCHES.5.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.6.name}}-{{BATCHES.6.type}}-V{{BATCHES.6.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.7.name}}-{{BATCHES.7.type}}-V{{BATCHES.7.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}"  }
 - { src: "/tmp/{{hostvars['localhost'].EXT_DIR}}/{{BATCHES.8.name}}-{{BATCHES.8.type}}-V{{BATCHES.8.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}"  }

BATCH_UNARCHIVE:
 - { src: "/tmp/libperl.gz" , dest: "{{BATCH_APP_BASE}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}/{{BATCHES.0.name}}-{{BATCHES.0.type}}-V{{BATCHES.0.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}/{{BATCHES.1.name}}-{{BATCHES.1.type}}-V{{BATCHES.1.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}/{{BATCHES.2.name}}-{{BATCHES.2.type}}-V{{BATCHES.2.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}/{{BATCHES.3.name}}-{{BATCHES.3.type}}-V{{BATCHES.3.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}/{{BATCHES.4.name}}-{{BATCHES.4.type}}-V{{BATCHES.4.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}/{{BATCHES.5.name}}-{{BATCHES.5.type}}-V{{BATCHES.5.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}/{{BATCHES.6.name}}-{{BATCHES.6.type}}-V{{BATCHES.6.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}/{{BATCHES.7.name}}-{{BATCHES.7.type}}-V{{BATCHES.7.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}/{{BATCHES.8.name}}-{{BATCHES.8.type}}-V{{BATCHES.8.version}}.tar.gz" , dest: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}/binpackage/{{BATCHES.0.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}/binpackage/{{BATCHES.1.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}/binpackage/{{BATCHES.2.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}/binpackage/{{BATCHES.3.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}/binpackage/{{BATCHES.4.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}/binpackage/{{BATCHES.5.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}/binpackage/{{BATCHES.6.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}/binpackage/{{BATCHES.7.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch" , remote_src: yes }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}/binpackage/{{BATCHES.8.name}}.tgz" , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch" , remote_src: yes }


BATCH_SYNCHRONIZE:
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.0.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.1.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.2.name}}/conf/" 	  	    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.3.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.4.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.5.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.6.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.7.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch/etc" }
 - { src: "{{EXTRACT_DIR}}/{{BATCHES.8.name}}/conf/" 		    	  , dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch/etc" }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/bin/init.d/" , dest: /etc/init.d 				      		  }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch/bin/init.d/" , dest: /etc/init.d 				      		  }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch/bin/init.d/" , dest: /etc/init.d 				      		  }

BATCH_FILE_2:
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/var/log" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/var/run" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch" 	       , owner: serveur , group: serveur , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch" 	       , owner: serveur , group: serveur , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch" 	       , owner: serveur , group: serveur , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch/var/log" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch/var/run" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch/var/log" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch/var/run" , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch" 	       , owner: stats   , group: stats   , recurse: yes }
 - { path: "/etc/init.d/convPcnV2"        , owner: root , group: root , recurse: no }
 - { path: "/etc/init.d/gvStatManager"    , owner: root , group: root , recurse: no }
 - { path: "/etc/init.d/gvStatCalculator" , owner: root , group: root , recurse: no }

BATCH_FILE_3:
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.0.name}}" , owner: root , group: root , state: link }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.1.name}}" , owner: root , group: root , state: link }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.2.name}}" , owner: root , group: root , state: link }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.3.name}}" , owner: root , group: root , state: link }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.7.name}}" , owner: root , group: root , state: link }
 - { src: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch/etc/cron" , dest: "/etc/cron.d/{{BATCHES.8.name}}" , owner: root , group: root , state: link }


BATCH_REPLACE:
################################################  batch convPcnV2  ##################################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/etc/cron"
   changes:
    - { regexp: /usr2/batch/convPcnV2			 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.0.name}}/batch/bin/retreivePcn.sh"
   changes:
    - { regexp: itggv-ip01c.omsccs94.cvf		 , replace: OMS01 }
 - dest: /etc/init.d/convPcnV2
   changes:
    - { regexp: /usr2/batch			 	 , replace: "{{BATCH_APP_BASE}}/batch" }
##################################################  batch gv-batch  #################################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch/etc/cron"
   changes:
    - { regexp: /usr2/batch/gv-batch			 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch/etc/hibernateStatMaster.cfg.xml"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs      	 , replace: "{{DB_VIP}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.1.name}}/batch/etc/hibernate.cfg.xml"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 		 , replace: "{{DB_VIP}}" }
##################################################  batch gv-stats-stp ## ############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch/etc/cron"
   changes:
    - { regexp: /usr2/batch/gv-stats-stp     		 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.2.name}}/batch/etc/gvaa-stats.properties"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 		 , replace: "{{DB_VIP}}" }
####################################################  batch gv-tools   ###############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.3.name}}/batch/etc/hibernate.cfg.xml"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs 		 , replace: "{{DB_VIP}}" }
################################################  batch stats-calculator  ############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}/batch/etc/stats-calculator.cfg"
   changes:
    - { regexp: /usr2/batch/stats-calculator      	 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.4.name}}" }
    - { regexp: cloud-amea02-itg.ope.cloud.mbs   	 , replace: "{{DB_VIP}}" }
 - dest: /etc/init.d/gvStatCalculator
   changes:
    - { regexp: /usr2/batch				 , replace: "{{BATCH_APP_BASE}}/batch" }
################################################  batch stats-manager  ##############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}/batch/etc/statManagerOms.cfg"
   changes:
    - { regexp: /usr2/batch/stats-manager         	 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.5.name}}" }
    - { regexp: cloud-amea02-itg.ope.cloud.mbs   	 , replace: "{{DB_VIP}}" }
 - dest: /etc/init.d/gvStatManager
   changes:
    - { regexp: /usr2/batch				 , replace: "{{BATCH_APP_BASE}}/batch" }
#########################################  batch stats-manager-reintegration  #######################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}/batch/etc/statManager.cfg"
   changes:
    - { regexp: /usr2/batch/stats-manager-reintegration  , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.6.name}}" }
    - { regexp: cloud-amea02-itg.ope.cloud.mbs		 , replace: "{{DB_VIP}}" }
###########################################  batch stats-rapatriement ### ############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch/etc/cron"
   changes:
    - { regexp: /usr2/batch/stats-rapatriement           , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.7.name}}/batch/etc/stats_rapatriement.cfg"
   changes:
    - { regexp: cloud-amea02-itg.ope.cloud.mbs   	 , replace: "{{DB_VIP}}" }
###############################################  batch stats-utilities  ##############################################
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch/etc/cron"
   changes:
    - { regexp: /usr2/batch/stats-utilities          	 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch/etc/stats-analyzer.cfg"
   changes:
    - { regexp: /usr2/batch/stats-utilities          	 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}" }
    - { regexp: cloud-amea02-itg.ope.cloud.mbs   	 , replace: "{{DB_VIP}}" }
 - dest: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}/batch/etc/stats-purgeTemporaryTables.cfg"
   changes:
    - { regexp: /usr2/batch/stats-utilities          	 , replace: "{{BATCH_APP_BASE}}/batch/{{BATCHES.8.name}}" }
    - { regexp: cloud-amea02-itg.ope.cloud.mbs   	 , replace: "{{DB_VIP}}" }
############################################       syslog.conf        ##############################################
 - dest: "/etc/syslog.conf"
   changes:
    - { regexp: '#\$ModLoad imudp' , replace: '$ModLoad imudp' }
    - { regexp: '#\$UDPServerRun 514' , replace: '$UDPServerRun 514' }
    - { regexp: '^local7\.\*.*' , replace: 'local7.*           /opt/application/ivraas/current/logs/ivraas_batch.log' }

