---

DATA_BASES:
  - StatVoxProdV2
  - StatVoxProdV2Tmp
  - exploitvocalAdmin
  - exploitvocalProd
  - gvw
  - gvw_logs

SQL_SCRIPTS:
  - db-stats-struct.sql
  - db-stats-data.sql
  - db-gvw-initUserAndDb.sql   
  - db-gvw-struct_12.4.12.sql   
  - db-gvw_logs-initUserAndDb.sql 
  - db-gvw_logs-struct_12.4.12.sql

