---

- name: Shell-- Get the extracted directory name of the {{IVRAAS_SOURCE}}
  shell: " tar -tf {{IVRAAS_SOURCE}} |head -n 1 | cut -d/ -f1 "
  args:
    warn: false
  register: OUTPUT1
  tags: prepare

- set_fact:
    EXT_DIR: "{{OUTPUT1.stdout}}"
    cacheable: true
  tags: prepare

- name: Unarchive-- Unarchive {{IVRAAS_SOURCE}} to /tmp
  unarchive:
    src: "{{IVRAAS_SOURCE}}"
    dest: /tmp
    creates: "/tmp/{{EXT_DIR}}/"
  tags: prepare

- name: Shell-- Get the webapps versions
  shell: for i in gv-admmsgvocale-svi gv-authent gv-provisioning gv-switchingservice gv-webservices gv-svifiles gv-admin-stp gv-adv gv-stats gv-vocalmestre; do ls $i* |grep -i webapp |grep -oP '(?<=-V).*(?=.tar)';done
  args:
    chdir: "/tmp/{{EXT_DIR}}/"
  register: OUTPUT2
  tags: prepare

- set_fact:
    WEBAPPS_VERSIONS: "{{OUTPUT2.stdout_lines}}"
    cacheable: true
  tags: prepare

- name: Shell-- Get the batches versions
  shell: ls |grep -i batch |grep -oP '(?<=-V).*(?=.tar)'
  args:
    chdir: "/tmp/{{EXT_DIR}}/"
  register: OUTPUT3
  tags: prepare

- set_fact:
    BATCHES_VERSIONS: "{{OUTPUT3.stdout_lines}}"
    cacheable: true
  tags: prepare

- name: Archive-- Archive {{playbook_dir}}/files/{{IVRAAS_TAR_NAME}}/sql
  archive:
    path: "/tmp/{{EXT_DIR}}/libperl"
    dest: "/tmp/{{EXT_DIR}}/libperl.gz"
#    remove: yes
  tags: prepare
#
#- name: Archive-- Archive "{{playbook_dir}}/files/{{IVRAAS_TAR_NAME}}/*webapp*"
#  archive:
#    path: "{{playbook_dir}}/files/{{IVRAAS_TAR_NAME}}/*webapp*"
#    dest: "{{playbook_dir}}/files/{{IVRAAS_TAR_NAME}}/webapps.gz"
#    remove: yes
#  tags: prepare




