---

- name: File-- Create web applications directories
  file:
    dest: "{{item.dest}}"
    state: "{{item.state}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items: "{{WAS_FILE}}"
  tags: was

- name: Template-- Templating mod_jk.conf, worker.properties and apache virtual hosts configuration files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items: "{{WAS_TEMPLATE}}"
  tags: was

- name: Copy-- Copy Webapps under {{EXTRACT_DIR}} 
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items: "{{WAS_COPY1}}"
  tags: was

- name: Unarchive-- extract webapps into deployment dirs
  unarchive:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{WAS_UNARCHIVE}}"
  tags: was

- name: Synchronize-- Copy conf/ to META-INF
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{WAS_SYNCHRONIZE}}"
  tags: was

- name: Copy-- Copy context.xml under Catalina 
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{WAS_COPY2}}"
  tags: was

- name: Lineinfile-- Modify {{TOMCAT_CONF}}/server.xml and {{TOMCAT_CONF}}/tomcat6.conf 
  lineinfile:
    dest: "{{item.dest}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{WAS_LINEINFILE}}"
  notify: "restart web service"
  tags: was

- name: Blockinfile-- Modify {{TOMCAT_CONF}}/server.xml to add virtual hosts and {{TOMCAT_CONF}}/tomcat-users.xml to add users and roles 
  blockinfile:
    dest: "{{item.dest}}"
    insertafter: "{{item.insertafter}}"
    marker: "{{item.marker}}"
    block: "{{item.block}}"
  with_items: "{{WAS_BLOCKINFILE}}"
  notify: "restart web service"
  tags: was

- name : Replace-- set key values in configuration files
  replace:
    dest: "{{item.0.dest}}"
    regexp: "{{item.1.regexp}}"
    replace: "{{item.1.replace}}"
  with_subelements: 
   - "{{WAS_REPLACE}}"
   - changes
  notify: "restart web service"
  tags: was

- name: File-- Chown -R ivruser. /opt/application/ivraas/{{IVRAAS_VERSION}}/
  file:
    path: /opt/application/ivraas/{{IVRAAS_VERSION}}/
    owner: ivruser
    group: ivrgroup
    recurse: yes
  tags: was
