---
##########################################################################################################################
#                                               pre apache,tomcat tasks                                                  #
##########################################################################################################################


- name: Ensure sox s installed
  yum:
    name: sox
    state: latest
  become: yes
  tags: pre_was

- name: Mount up nfs volume
  mount:
    name: /mntcvf/web_rw
    src: ubuntu:/ubuntu
    fstype: nfs
    opts: rw,rsize=32768,wsize=32768,tcp
    state: mounted
  become: yes
  tags: pre_was

- name: Create directory tree inside nfs directory
  file:
    path: /mntcvf/web_rw/gv-data/{{item}}
    state: directory
#   owner: tomcat
#   group: tomcat
  with_items:
    - mevo
    - services
    - statistiques
  become: yes
  tags: pre_was

