---

TOMCAT_TAR: PA-TOM-R6T80-RDG02R02C04.tar
TOMCAT_VERSION: 8.0.36

appliId: ivraas
appliVersion: "{{IVRAAS_VERSION}}"
owner: ivruser
groupe: ivrgroup
shutdownPort: 9801
httpPort: 9080
httpsPort: "NO"
ajpPort: 9089
jmxPort: "NO"

