---

- debug:
    msg: "{{hostvars['localhost'].BATCHES_VERSIONS.0}}" 
  tags: batch-test 

- name: Yum-- Install mysql, mysql-devel and nfs-utils.x86_64
  yum:
    name:
     - mysql
     - mysql-devel
     - nfs-utils.x86_64
    state: latest
  tags: batch

- name: Group-- Create groups stats,serveur and group
  group:
    name: "{{item.name}}"
    gid: "{{item.gid}}"
  with_items: "{{BATCH_GROUP}}"
  tags: batch

- name: User-- Create users stats,serveur and ivruser
  user:
    name: "{{item.name}}"
    uid: "{{item.uid}}"
    group: "{{item.group}}" 
  with_items: "{{BATCH_USER}}"
  tags: batch

- name: Lineinfile-- Set SHARED_LIB_PERL environment variable of stats user
  lineinfile:
     dest: /home/stats/.bashrc
     line: "export SHARED_LIB_PERL={{BATCH_APP_BASE}}/libperl"
  tags: batch

- name: File-- Create {{BATCH_APP_BASE}}/batch/<batches>/batch , {{EXTRACT_DIR}}/<batches> and /mnt/statvox2/var shared directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_1}}"
  tags: batch

- name: Copy-- Copy batches to {{EXTRACT_DIR}} and libperl to {{BATCH_APP_BASE}}
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items: "{{BATCH_COPY}}"
  tags: batch

- name: Unarchive-- extract libperl.zip and batches 
  unarchive:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{BATCH_UNARCHIVE}}"
  tags: batch

- name: Synchronize-- copy conf/ to etc/ and batch/bin/init.d/ to /etc/init.d
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{BATCH_SYNCHRONIZE}}"
  tags: batch

- name: File-- Set owner and group for synchronized files and directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    recurse: "{{item.recurse}}"
  with_items: "{{BATCH_FILE_2}}"
  tags: batch

- name: File-- create soft links under /etc/cron.d
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_3}}"
  tags: batch

- name : Replace-- set key values in configuration files
  replace:
    dest: "{{item.0.dest}}"
    regexp: "{{item.1.regexp}}"
    replace: "{{item.1.replace}}"
  with_subelements:
   - "{{BATCH_REPLACE}}"
   - changes
  tags: batch


