---

- name: Yum-- Install mysql, mysql-devel and nfs-utils.x86_64
  yum:
    name:
     - mysql
     - mysql-devel
     - nfs-utils.x86_64
    state: latest
  tags: batch

- name: Group-- Create groups stats,serveur and group
  group:
    name: "{{item.name}}"
    gid: "{{item.gid}}"
  with_items: "{{BATCH_GROUP}}"
  tags: batch

- name: User-- Create users stats,serveur and ivruser
  user:
    name: "{{item.name}}"
    uid: "{{item.uid}}"
    group: "{{item.group}}" 
  with_items: "{{BATCH_USER}}"
  tags: batch

- name: Lineinfile-- Set SHARED_LIB_PERL environment variable of stats user
  lineinfile:
     dest: /home/stats/.bashrc
     line: "export SHARED_LIB_PERL={{BATCH_APP_BASE}}/libperl"
  tags: batch

- name: File-- Create {{BATCH_APP_BASE}}/batch/<batches>/batch , {{EXTRACT_DIR}}/<batches> and /mnt/statvox2/var shared directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_1}}"
  tags: batch

- name: File-- Create symbolic link 
  file:
    src: "{{BATCH_APP_BASE}}"
    dest: "/opt/application/ivraas/current"
    state: link
  tags: batch

- name: Copy-- Copy batches to {{EXTRACT_DIR}} and libperl.gz to /tmp
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: no
  with_items: "{{BATCH_COPY}}"
  tags: batch

- name: Unarchive-- extract libperl.zip and batches 
  unarchive:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{BATCH_UNARCHIVE}}"
  tags: batch

- name: Synchronize-- copy conf/ to etc/ and batch/bin/init.d/ to /etc/init.d
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{BATCH_SYNCHRONIZE}}"
  tags: batch

- name: File-- Set owner and group for synchronized files and directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    recurse: "{{item.recurse}}"
  with_items: "{{BATCH_FILE_2}}"
  tags: batch

- name: File-- create soft links under /etc/cron.d
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_3}}"
  tags: batch

- name : Replace-- set key values in configuration files
  replace:
    dest: "{{item.0.dest}}"
    regexp: "{{item.1.regexp}}"
    replace: "{{item.1.replace}}"
  with_subelements:
   - "{{BATCH_REPLACE}}"
   - changes
  tags: batch

- name: Blockinfile-- Insert/update WAS1 Vhosts in /etc/hosts in batch1
  blockinfile:
    path: /etc/hosts
    block: |
      172.16.2.217    OMS01
      # WAS 1 VHosts
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	gv-admmsgvocale-svi-amea.dmz.cloud.mbs
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	gv-provisioning-amea.dmz.cloud.mbs
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	gv-switchingservice-amea.dmz.cloud.mbs
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	gv-webservices-amea.dmz.cloud.mbs
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	gv-svifiles-amea.dmz.cloud.mbs
      {{hostvars['was1'].ansible_eth1.ipv4.address}}	{{URL}}
  when: inventory_hostname == "batch1"
  tags: batch

- name: Blockinfile-- Insert/update WAS2 Vhosts in /etc/hosts in batch2
  blockinfile:
    path: /etc/hosts
    block: |
      172.16.2.217    OMS01
      # WAS 1 VHosts
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	gv-admmsgvocale-svi-amea.dmz.cloud.mbs
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	gv-provisioning-amea.dmz.cloud.mbs
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	gv-switchingservice-amea.dmz.cloud.mbs
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	gv-webservices-amea.dmz.cloud.mbs
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	gv-svifiles-amea.dmz.cloud.mbs
      {{hostvars['was2'].ansible_eth1.ipv4.address}}	{{URL}}
  when: inventory_hostname == "batch2"
  tags: batch

- name: Lineinfile-- add MAILTO="" n the gv-batch cron job
  lineinfile:
    path: "/opt/application/ivraas/{{IVRAAS_VERSION}}/batch/gv-batch/batch/etc/cron"
    insertbefore: BOF
    line: 'MAILTO=""'
  tags: batch

