---
- name: MYSQL | install mysql client and server
  yum:
    name:
     - mysql
     - mysql-devel
    state: latest
  become: yes
#  tags: batch

- name: Create user stats 
  user:
    name: stats
  become: yes
  tags: batch

- name: Create user serveur
  user:
    name: serveur
  become: yes
  tags: batch

- name: Create group tomcat gid 91
  group:
    name: tomcat
    gid: 91
    state: present
  become: yes
  tags: batch

- name: Cerate user tomcat uid 91
  user: 
    name: tomcat
    uid: 91
    group: tomcat
  become: yes
  tags: batch

- name: Create web application and logs directories
  file:
    path: "{{item.path}}"
    state: directory
    owner: "{{item.owner}}"
  with_items: "{{batch_directories}}"
  become: yes
  tags: batch

- name: Copy the libperl.zip to {{EXTRACT_DIR}}
  copy:
    src: libperl.zip
    dest: "{{EXTRACT_DIR}}"
  become: yes
  tags: batch

- name: Unzip {{EXTRACT_DIR}}libperl.zip into /usr2/batch/libperl
  command : unzip "{{EXTRACT_DIR}}"libperl.zip 
  args:
    chdir: /usr2/batch/
    creates: /usr2/batch/libperl/Algorithm/Diff/XS.pm
  become: yes
  tags: batch

- name: Export environment variable of stats user
  lineinfile:
     dest: /home/stats/.bashrc
     line: export SHARED_LIB_PERL=/usr2/batch/libperl
  become: yes
  tags: batch

- name: Unarchive {{BATCH_ZIP_FILENAME}}.zip into {{EXTRACT_DIR}}
  unarchive:
    src: "{{BATCH_ZIP_FILENAME}}.zip"
    dest: "{{EXTRACT_DIR}}"
  tags: batch

- name: Copy batch.sh to {{EXTRACT_DIR}}
  copy:
    src: batch.sh
    dest: "{{EXTRACT_DIR}}"
    mode: 0550
  become: yes
  tags: batch
 
- name: Place batches in its place
  shell: MODULE="{{item.NAME}}" FULL_FILENAME="{{EXTRACT_DIR}}""{{BATCH_ZIP_FILENAME}}"/"{{item.NAME}}"-"{{item.TYPE}}"-"{{item.VERSION}}".tar.gz ./batch.sh >> /tmp/batch.sh_output 2>&1
  args:
    chdir: "{{EXTRACT_DIR}}"
#    creates: "{{item.dir}}/META-INF"
  with_items: "{{BATCHES}}"
  become: yes
  tags: batch

