---

##################################################################################
#                           Install Oracle Java Jdk                              #
##################################################################################


- name: Copy java jdk8 to {{EXTRACT_DIR}}
  copy:
    src: "{{JAVA_RPM}}"
    dest: "{{EXTRACT_DIR}}"
  tags: java
 

- name: Install Java 8
  yum:
    name: "{{EXTRACT_DIR}}/{{JAVA_RPM}}"
  become: yes
  tags: java


- name: Correct java version selected
  alternatives:
    name: java
    path: "{{JAVA_HOME}}/java"
  become: yes
  tags: java



- shell: ls -I common-media* /etc/yum.repos.d/
  register: result
  become: yes
  tags: common


- name: Ensure all yum repos are enabled
  replace:
    dest: /etc/yum.repos.d/{{item}}
    regexp: 'enabled=0'
    replace: 'enabled=1'
  with_items: "{{result.stdout_lines}}"
  become: yes
  tags: common


- name: Mount up nfs volume
  mount:
    name: /mntcvf/web_rw
    src: ubuntu:/ubuntu
    fstype: nfs
    opts: rw,rsize=32768,wsize=32768,tcp 
    state: mounted
  become: yes
  tags: nfs

- name: Create directory tree inside nfs directory
  file:
    path: /mntcvf/web_rw/gv-data/{{item}}
    state: directory
#   owner: tomcat
#   group: tomcat
  with_items:
    - mevo
    - services
    - statistiques
  become: yes
  tags: nfs 


#################################################################################
#										#
#################################################################################

- name: Yum-- install mysql client and server
  yum:
    name:
     - mysql
     - mysql-devel
    state: latest
#  tags: batch

#################################################################################
#										#
#################################################################################


- name: Group-- Create groups stats,serveur and tomcat
  group:
    name: "{{item.name}}"
    gid: "{{item.gid}}"
  with_items: "{{BATCH_GROUP}}"
  tags: batch

- name: User-- Create users stats,serveur and tomcat 
  user:
    name: "{{item.name}}"
    uid: "{{item.uid}}"
    group: "{{item.group}}" 
  with_items: "{{BATCH_USER}}"
  tags: batch

- name: Lineinfile-- set SHARED_LIB_PERL environment variable of stats user
  lineinfile:
     dest: /home/stats/.bashrc
     line: "export SHARED_LIB_PERL={{BATCH_APP_BASE}}/libperl"
  tags: batch

- name: File-- Create {{BATCH_APP_BASE}}/<batches>/batch , {{EXTRACT_DIR}}/<batches> and /mnt/statvox2/var shared directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_1}}"
  tags: batch

- name: Unarchive-- extract libperl.zip and batches 
  unarchive:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{BATCH_UNARCHIVE}}"
  tags: batch

- name: Synchronize-- copy conf/ to etc/ and batch/bin/init.d/ to /etc/init.d
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{BATCH_SYNCHRONIZE}}"
  tags: batch

- name: File-- Set owner and group for synchronized files and directories
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    recurse: "{{item.recurse}}"
  with_items: "{{BATCH_FILE_2}}"
  tags: batch

- name: File-- create soft links under /etc/cron.d
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: "{{item.state}}"
  with_items: "{{BATCH_FILE_3}}"
  tags: batch

- name : Replace-- set key values in configuration files
  replace:
    dest: "{{item.0.dest}}"
    regexp: "{{item.1.regexp}}"
    replace: "{{item.1.replace}}"
  with_subelements:
   - "{{BATCH_REPLACE}}"
   - changes
  tags: batch


