---

TOMCAT_LINEINFILE:
 - dest: "{{TOMCAT_CONF}}/server.xml"
   regexp: '<Connector port="8009"'
   line: >
          '<Connector port="8009" maxThreads="800" connectionTimeout="60000" minSpareThreads="25"
           maxSpareThreads="75" enableLookups="false" protocol="AJP/1.3" redirectPort="8443" />'

 - dest: "{{TOMCAT_CONF}}/server.xml"
   regexp: '<Engine name="Catalina" defaultHost="localhost'
   line: '<Engine name="Catalina" defaultHost="localhost" jvmRoute="localhost">'

 - dest: "{{TOMCAT_CONF}}/tomcat6.conf"
   regexp: 'JAVA_OPTS='
   line: >
          'JAVA_OPTS="${JAVA_OPTS} -Xmx1536m -Xms1024m -Xmn512m -XX:MaxPermSize=512m -Djavax
          .sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory"'


TOMCAT_BLOCKINFILE:
 - dest: "{{TOMCAT_CONF}}/tomcat-users.xml"
   insertafter: "<tomcat-users>"
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
   block: "{{ lookup('file', 'tomcat-users') }}" 
 - dest: "{{TOMCAT_CONF}}/server.xml"
   insertafter: 
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
#   block: "{{ lookup('file', 'vhosts') }}"
   block: ' |
         <Host name="gv-authent-amea.dmz.cloud.mbs" appBase="/usr2/web/gv-authent-amea.dmz.cloud.mbs" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false"> 
         </Host>
         
         <Host name="gv-admmsgvocale-svi-amea.dmz.cloud.mbs" appBase="/usr2/web/gv-admmsgvocale-svi-amea.dmz.cloud.mbs" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false">
         </Host>

         <Host name="gv-switchingservice-amea.dmz.cloud.mbs" appBase="/usr2/web/gv-switchingservice-amea.dmz.cloud.mbs" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false"> 
         </Host>

         <Host name="gv-webservices-amea.dmz.cloud.mbs" appBase="/usr2/web/gv-webservices-amea.dmz.cloud.mbs" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false"> 
         </Host>

         <Host name="gv-provisioning-amea.dmz.cloud.mbs" appBase="/usr2/web/gv-provisioning-amea.dmz.cloud.mbs" unpackWARs="false" liveDeploy="false" autoDeploy="false" deployOnStartup="true" deployXML="false"> 
         </Host> '

TOMCAT_FILE:
 - { path: "{{TOMCAT_CONF}}/Catalina/gv-admmsgvocale-svi-{{WEB_DOMAIN}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/gv-provisioning-{{WEB_DOMAIN}}"	 , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/gv-switchingservice-{{WEB_DOMAIN}}" , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/gv-authent-{{WEB_DOMAIN}}" 	 , state: directory }
 - { path: "{{TOMCAT_CONF}}/Catalina/gv-webservices-{{WEB_DOMAIN}}" 	 , state: directory }


TOMCAT_COPY:
 - { src: manager.xml , dest: "{{TOMCAT_HOME}}/conf/Catalina/localhost/" 		     } 
 - { src: manager.xml , dest: "{{TOMCAT_CONF}}/Catalina/gv-admmsgvocale-svi-{{WEB_DOMAIN}}/" } 
 - { src: manager.xml , dest: "{{TOMCAT_CONF}}/Catalina/gv-provisioning-{{WEB_DOMAIN}}/"     } 
 - { src: manager.xml , dest: "{{TOMCAT_CONF}}/Catalina/gv-switchingservice-{{WEB_DOMAIN}}/" } 
 - { src: manager.xml , dest: "{{TOMCAT_CONF}}/Catalina/gv-authent-{{WEB_DOMAIN}}/" 	     } 
 - { src: manager.xml , dest: "{{TOMCAT_CONF}}/Catalina/gv-webservices-{{WEB_DOMAIN}}/"      } 

TOMCAT_UNARCHIVE: 
 - { src: "{{WEB_ZIP_FILENAME}}.zip" , dest: "{{EXTRACT_DIR}}" } 

TOMCAT_APPS_OBJS:
 - { NAME: "{{WEB_APPS.0.NAME}}" , VERSION: "{{WEB_APP.0.VERSION}}" , PATH: /ROOT	  }
 - { NAME: "{{WEB_APPS.1.NAME}}" , VERSION: "{{WEB_APP.1.VERSION}}" , PATH: /ROOT	  }
 - { NAME: "{{WEB_APPS.2.NAME}}" , VERSION: "{{WEB_APP.2.VERSION}}" , PATH: /ROOT 	  }
 - { NAME: "{{WEB_APPS.3.NAME}}" , VERSION: "{{WEB_APP.3.VERSION}}" , PATH: /ROOT 	  }
 - { NAME: "{{WEB_APPS.4.NAME}}" , VERSION: "{{WEB_APP.4.VERSION}}" , PATH: /ROOT 	  }
 - { NAME: "{{WEB_APPS.5.NAME}}" , VERSION: "{{WEB_APP.5.VERSION}}" , PATH: /ROOT	  }
 - { NAME: "{{WEB_APPS.6.NAME}}" , VERSION: "{{WEB_APP.6.VERSION}}" , PATH: /admin-stp	  }
 - { NAME: "{{WEB_APPS.7.NAME}}" , VERSION: "{{WEB_APP.7.VERSION}}" , PATH: /adv1	  }
 - { NAME: "{{WEB_APPS.8.NAME}}" , VERSION: "{{WEB_APP.8.VERSION}}" , PATH: /stats	  }
 - { NAME: "{{WEB_APPS.9.NAME}}" , VERSION: "{{WEB_APP.9.VERSION}}" , PATH: /vocalmestre1 }


