---

#########################################################################################
#											#
#########################################################################################

- name: YUM-- install mysql client and server
  yum:
    name:
     - mysql
     - mysql-server
    state: latest
  tags: mysql

- name: COPY-- copy Mysql-python to {{ECTRACT_DIR}}
  copy:
    src: MySQL-python-1.2.3-0.3.c1.1.el6.x86_64.rpm
    dest: "{{EXTRACT_DIR}}/MySQL-python-1.2.3-0.3.c1.1.el6.x86_64.rpm"
    owner: root
    group: root
  tags: mysql

- name: YUM-- install MySQL-python to enable mysql_user module
  yum:
    name: /tmp/IVRaaS/MySQL-python-1.2.3-0.3.c1.1.el6.x86_64.rpm
    state: present
  become: yes
  tags: mysql

- name: Service-- Ensure mysqld is started and enabled 
  service:
    name: mysqld
    state: started
    enabled: yes
  tags: mysql 

#########################################################################################
#											#
#########################################################################################


- name: Mysql_user-- Update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: localhost 
    password: "{{MYSQL_ROOT_PASS}}"
  tags: mysql

- name: Blockinfile-- insert/update "[client]" configuration block in /root/.my.cnf
  blockinfile:
    dest: /root/.my.cnf
    block: |
      [client]
      password={{MYSQL_ROOT_PASS}}
    create: yes
    mode: 0600
  tags: mysql

- name: Mysql_db-- Create new databases 
  mysql_db:
    name: "{{item}}"
    state: present 
  with_items: "{{DATA_BASES}}"
  tags: mysql

- name: Copy-- copy sql scripts to {{EXTRACT_DIR}}/sql_sqripts
  copy:
    src: sql_scripts
    dest: "{{EXTRACT_DIR}}"
  become: yes
  tags: mysql 

- name : Replace-- set recipient of marketing report and current deployment country keys in sql scripts
  replace:
    dest: "{{item.dest}}"
    regexp: "{{item.regexp}}"
    replace: "{{item.replace}}" 
  with_items: "{{MYSSQL_REPLACE}}"

- name: Mysql_db-- Import sql sqripts
  mysql_db:
    state: import
    name: all
    target: "{{EXTRACT_DIR}}/sql_scripts/{{item}}"
  with_items: "{{SQL_SCRIPTS}}"
  become: yes
  tags: mysql
