---

- name: Copy-- copy {{MYSQL_TAR}} to /tmp
  copy: 
    src: "{{MYSQL_TAR}}"
    dest: /tmp
  tags: pli-mysql

- name: File-- create directory /images/mysql/{{MYSQL_VERSION}}
  file:
    path: "/images/mysql/{{MYSQL_VERSION}}/"
    state: directory
  tags: pli-mysql

- name: Stat-- Check if /opt/mysql/na/{{MYSQL_VERSION}} exist 
  stat:
    path: "/opt/mysql/na/{{MYSQL_VERSION}}"
  register: Dir_existance
  tags: pli-mysql

- name: Unarchive-- /tmp/{{MYSQL_TAR}} into /images/mysql/{{MYSQL_VERSION}}/
  unarchive:
    src: "/tmp/{{MYSQL_TAR}}"
    dest: "/images/mysql/{{MYSQL_VERSION}}/"
    remote_src: yes
  when: not Dir_existance.stat.exists
  tags: pli-mysql

- name: Shell-- run my_instbin.ksh {{MYSQL_VERSION}} 2 silent
  shell: "./my_instbin.ksh {{MYSQL_VERSION}} 2 silent"
  args:
    chdir: "/images/mysql/{{MYSQL_VERSION}}"
    creates: "/opt/mysql/na/{{MYSQL_VERSION}}"
  tags: pli-mysql

- name: User-- change the user "mysql" password
  user:
    name: mysql
    password: "{{PASSWD}}" 
  tags: pli-mysql

- name: Lineinfile-- Add the line {{DB_VIP}}  bdd-vip in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{DB_VIP}}  bdd-vip"
    state: present
  tags: pli-mysql

#########################################################################################
#				Preproduction						#
#########################################################################################
  
- name: Copy-- Copy myserver01.conf to /opt/mysql/bin/myserver01.conf --- Preproduction only ---
  copy:
    src: myserver01.conf
    dest: /opt/mysql/bin/myserver01.conf
  register: conf_file
  when: inventory_file|basename == "preproduction.inventory"
  tags: pli-mysql

- name: Shell-- Run the command "./my_createsrv.ksh myserver01 5.6.35 silent" --- Preproduction only ---
  shell: "./my_createsrv.ksh myserver01 5.6.35 silent"
  args:
    chdir: /opt/mysql/bin
    creates: /myqdata/myserver01/data/my.cnf
  when: inventory_file|basename == "preproduction.inventory"
  tags: pli-mysql

#########################################################################################
#				Production						#
#########################################################################################

- name: Copy-- Copy my_failover_db_nas.conf to /opt/mysql/bin/my_failover_db_nas.conf --- Production only ---
  copy:
    src: my_failover_db_nas.conf
    dest: /opt/mysql/bin/my_failover_db_nas.conf
  register: conf_file
  when: inventory_file|basename == "production.inventory"
  tags: pli-mysql

- name: Shell-- Run the command ksh /opt/mysql/bin/my_failover_db_nas.ksh init --- Production only ---
  run_once: true
  delegate_to: db1
  shell: ' ksh /opt/mysql/bin/my_failover_db_nas.ksh init'
  args:
    chdir: /opt/mysql/bin
    creates: /myqdata/myserver01/data/my.cnf
  when: 
    - inventory_file|basename == "production.inventory"
    - conf_file.changed
  tags: pli-mysql

- name: Shell-- Start mysql service
  run_once: true
  delegate_to: db1
  shell: " /bin/ps -ef |/bin/grep -v grep | /bin/grep /opt/mysql || (/bin/rm -rf /myqdata/backup/bdd-vip*.lock; /sbin/service mysql start) "
  args:
    warn: false
  ignore_errors: yes
  tags: pli-mysql

#########################################################################################

- name: Lineinfile-- Add collation-server=latin1_swedish_ci in /myqdata/myserver01/data/my.cnf
  run_once:
  delegate_to: db1 
  lineinfile:
    dest: /myqdata/myserver01/data/my.cnf
    insertafter: "collation-server=latin1_general_ci"
    line: "collation-server=latin1_swedish_ci"
  tags: pli-mysql
    
- name: Replace-- Comment the line "sql-mode=*" in /myqdata/myserver01/data/my.cnf
  run_once: true
  delegate_to: db1
  replace:
    path: /myqdata/myserver01/data/my.cnf
    regexp: "^sql-mode="
    replace: "#sql-mode="
  tags: pli-mysql

- name: Replace-- Set the lower-case-table-names= 0 in /myqdata/myserver01/data/my.cnf
  run_once: true
  delegate_to: db1
  replace:
    path: /myqdata/myserver01/data/my.cnf
    regexp: "^lower-case-table-names=1"
    replace: "lower-case-table-names=0"
  tags: pli-mysql

- name: Shell-- Restart mysql
  run_once: true
  delegate_to: db1
  shell: "/sbin/service mysql restart"
  args:
    warn: false
  tags: pli-mysql

