---

#########################################################################################################################
#						Tomcat installation  						 	#
#########################################################################################################################

- name: Ensure tomcat is installed
  yum:
    name: tomcat6
    state: latest
  tags: tomcat

- name: Ensure tomcat server is started and enabled
  service:
    name: tomcat6
    enabled: yes
  tags: tomcat

#########################################################################################################################
#						Tomcat configurations							#
#########################################################################################################################

- name: File-- Create virtual hosts dirs under  {{TOMCAT_CONF}}/Catalina and dirs to extract webapps in {{EXTRACT_DIR}}
  file:
    path: "{{item.path}}"
    state: "{{item.state}}"
  with_items: "{{TOMCAT_FILE}}"
  tags: tomcat

- name: Unarchive-- extract {{WEB_ZIP_FILENAME}}.zip and webapps into {{EXTRACT_DIR}}
  unarchive:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{TOMCAT_UNARCHIVE}}"
  tags: tomcat

- name: Synchronize-- copy conf/ to META-INF
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{TOMCAT_SYNCHRONIZE}}"
  tags: tomcat

- name: Copy-- Copy tomcat manager/ app to {{TOMCAT_HOME}}/webapps/ , manager.xml under vhosts and context.xml to <appname>.xml 
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: "{{item.remote_src}}"
  with_items: "{{TOMCAT_COPY}}"
  tags: tomcat

- name: Lineinfile-- Modify {{TOMCAT_CONF}}/server.xml and {{TOMCAT_CONF}}/tomcat6.conf 
  lineinfile:
    dest: "{{item.dest}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{TOMCAT_LINEINFILE}}"
  notify: restart tomcat
  tags: tomcat

- name: Blockinfile-- Modify {{TOMCAT_CONF}}/server.xml to add virtual hosts and {{TOMCAT_CONF}}/tomcat-users.xml to add users and roles 
  blockinfile:
    dest: "{{item.dest}}"
    insertafter: "{{item.insertafter}}"
    marker: "{{item.marker}}"
    block: "{{item.block}}"
  with_items: "{{TOMCAT_BLOCKINFILE}}"
  notify: restart tomcat
  tags: tomcat

