---

##########################################################################################################################
#						common tasks for all hosts						 #
##########################################################################################################################

- name: Copy-- Copy ivraas_repo.tar to /home/osadmin
  unarchive:
    src: "{{ playbook_dir }}/IVRaaS_files/ivraas_repo.tar"
    dest: /images 
  tags: common

 
