---

##########################################################################################################################
#						common tasks for all hosts						 #
##########################################################################################################################

- name: Replace-- Configure /etc/sysconfig/keyboard KEYTABLE="us"
  replace:
    path: /etc/sysconfig/keyboard
    regexp: 'KEYTABLE=.*'
    replace: 'KEYTABLE="us"'
    backup: yes
  tags: common

- name: Replace-- Configure /etc/sysconfig/keyboard LAYOUT="us"
  replace:
    path: /etc/sysconfig/keyboard
    regexp: 'LAYOUT=.*'
    replace: 'LAYOUT="us"'
    backup: yes
  tags: common

- name: Shell-- Run the command loadkeys us
  shell: loadkeys us
  tags: common

- name: Replace-- Configure /etc/sysconfig/i18n LANG="en_US.utf8"
  replace:
    path: /etc/sysconfig/i18n
    regexp: 'LANG=.*'
    replace: 'LANG="en_US.utf8"'
    backup: yes
  tags: common
    
- name: Timezone-- Set timezone to "{{ TIME_ZONE }}"
  timezone:
    name: "{{ TIME_ZONE }}"
  tags: common

- name: Stat-- Check if /image/ivraas_repo/repodata exist
  stat:
    path: /images/ivraas_repo/repodata
  register: Dir_existance
  tags: common

- name: Uarchive-- Unarchive {{IVRAAS_REPO}} to /images
  unarchive:
    src: "{{IVRAAS_REPO}}"
    dest: /images
  when: not Dir_existance.stat.exists
  tags: common

- name: Yum_repository-- Add ivraas repository
  yum_repository:
    name: ivraas
    description: IVRaaS repo
    baseurl: file:///images/ivraas_repo
  tags: common

#- name: Yum-- Yum Update
#  yum:
#    name: '*'
#    state: latest
#    exclude: kernel*
#    skip_broken: yes
#    disablerepo: '*'
#    enablerepo: "ivraas"
#  tags: common
# 
