---

APACHE_LINEINFILE:
 - { dest: "{{APACHE_CONF}}/conf/httpd.conf" , line: "include conf/mod_jk.conf" }

APACHE_COPY:
 - { src: modules/ 	, dest: "{{APACHE_CONF}}/modules/"	}
 - { src: conf/		, dest: "{{APACHE_CONF}}/conf/"		}

APACHE_FILE:
 - { PATH: "{{WEB_APP_BASE}}/gv-admmsgvocale-svi-{{WEB_DOMAIN}}/ROOT" 	 } 
 - { PATH: "{{WEB_APP_BASE}}/gv-authent-{{WEB_DOMAIN}}/ROOT" 	 	 }	 
 - { PATH: "{{WEB_APP_BASE}}/gv-authent-{{WEB_DOMAIN}}/admin-stp" 	 }			
 - { PATH: "{{WEB_APP_BASE}}/gv-authent-{{WEB_DOMAIN}}/stats" 	 	 }
 - { PATH: "{{WEB_APP_BASE}}/gv-authent-{{WEB_DOMAIN}}/adv1" 	 	 }
 - { PATH: "{{WEB_APP_BASE}}/gv-authent-{{WEB_DOMAIN}}/vocalmestre1" 	 }
 - { PATH: "{{WEB_APP_BASE}}/gv-provisioning-{{WEB_DOMAIN}}/ROOT"	 }
 - { PATH: "{{WEB_APP_BASE}}/gv-svifiles-{{WEB_DOMAIN}}/ROOT"		 }
 - { PATH: "{{WEB_APP_BASE}}/gv-switchingservice-{{WEB_DOMAIN}}/ROOT"	 }
 - { PATH: "{{WEB_APP_BASE}}/gv-webservices-{{WEB_DOMAIN}}/ROOT"	 }
 - { PATH: "{{WEB_LOG_BASE}}/gv-admmsgvocale-svi-{{WEB_DOMAIN}}/current" }
 - { PATH: "{{WEB_LOG_BASE}}/gv-authent-{{WEB_DOMAIN}}/current"		 }
 - { PATH: "{{WEB_LOG_BASE}}/gv-provisioning-{{WEB_DOMAIN}}/current"	 }
 - { PATH: "{{WEB_LOG_BASE}}/gv-svifiles-{{WEB_DOMAIN}}/current"	 }
 - { PATH: "{{WEB_LOG_BASE}}/gv-switchingservice-{{WEB_DOMAIN}}/current" }
 - { PATH: "{{WEB_LOG_BASE}}/gv-webservices-{{WEB_DOMAIN}}/current"	 }
 - { PATH: "{{WEB_LOG_BASE}}/mod_jk/current"				 }



