---

- name: Copy-- copy {{APACHE_TAR}} to /tmp
  copy: 
    src: "{{APACHE_TAR}}"
    dest: /tmp
  tags: pli-apache

- name: File-- create directory /images/apache/{{APACHE_VERSION}}/
  file:
    path: "/images/apache/{{APACHE_VERSION}}/"
    state: directory
  tags: pli-apache

- name: Unarchive-- /tmp/{{APACHE_TAR}} into /images/apache/{{APACHE_VERSION}}/
  unarchive:
    src: "/tmp/{{APACHE_TAR}}"
    dest: "/images/apache/{{APACHE_VERSION}}/"
    remote_src: yes
  tags: pli-apache

- name: Shell-- Run apa_install.ksh
  shell: ./apa_install.ksh
  args:
    chdir: "/images/apache/{{APACHE_VERSION}}/"
    creates: "/opt/apache/{{APACHE_VERSION}}"
  async: 360
  register: sleeper_apa_install
  tags: pli-apache

- name: Shell-- Run apa_creinstance.ksh
  shell: "./apa_creinstance.ksh {{AppliId}} {{AppliType}} {{AppliVersion}} {{AppliGroup}} {{AppliUser}} {{AppliVg}} {{AppliLvSize}} {{Worker}} {{Http}} {{HttpPort}} {{Https}} {{HttpsPort}} {{AjpPort}} {{Interface}} {{Flag}}"
  args:
    chdir: /opt/apache/bin/
    creates: "/opt/application/{{AppliId}}/{{AppliVersion}}/apache*/conf.d/"
  async: 360
  register: sleeper_apa_crtinst
  tags: pli-apache

- name: Stat-- check if /opt/application/{{AppliId}}/current is linked to the IVRaaS version {{IVRAAS_VERSION}}
  stat:
    path: /opt/application/{{AppliId}}/current
  register: link
  tags: pli-apache

- name: Shell-- Run ./apa_changecurrent.ksh {{AppliId}} {{AppliVersion}}
  shell: "./apa_changecurrent.ksh {{AppliId}} {{AppliVersion}}"
  args:
    chdir: /opt/apache/bin/
  when: 
    -  (not link.stat.exists) or (link.stat.lnk_target|basename != AppliVersion)
  tags: pli-apache


